### ISSUE TITLE
Schrabidium pickaxe and all other tools with abilities break the serverside and don't work

### ISSUE THREAD

**Issue by Consumedgrub2** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#337] opened 2024-02-17 07:48 UTC
```
[01:28:55] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_392]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_392]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) ~[h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:861) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_392]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.hbm.util.I18nUtil.resolveKey(I18nUtil.java:8) ~[I18nUtil.class:2.0.1]
        at com.hbm.items.tool.ItemToolAbility.switchMode(ItemToolAbility.java:370) ~[ItemToolAbility.class:2.0.1]
        at com.hbm.items.tool.ItemToolAbility.func_180614_a(ItemToolAbility.java:325) ~[ItemToolAbility.class:2.0.1]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:839) ~[ForgeHooks.class:e586889b]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:210) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:614) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1141) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_392]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_392]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```
When joined on a server, whenever I change the tool ability on at least either the spiral drill, impact drill or schrabidium pickaxe, the ping sound and selected ability does not print to chat. On the server side, the top error is displayed after at least switching the tool ability on the schrabidium pickaxe. Then all blocks broken by the player do not update on the server side. This causes ghost blocks that other players see, but that don't exist and can't be interacted with on the end of the player who used the pickaxe cycle ability.

**Comment by Shibva** [comment] 2024-02-23 07:01
I wonder if the mod is also acting up the advancement system; its a complex issue that results in the advancement thing that detects objectives to break till something like going though the end restarts it or something

but yeah, no expert here but that sounds like some sort of desync happening; it could be possible some other mods present might be exaggerating this issue. Could you provide a modlist, you can generate one quickly by triggering the debug-crash (utility crash for debug purposes, triggered by holding the f3+C key for ~10 seconds. in the generated crashlog, there should be a list of all mods in the list loaded and printed

**Comment by Consumedgrub2** [comment] 2024-02-23 08:32
I'd like to add this is happening with the latest version of NTM being 2.0.1, since then I reverted the server to NTM 1.9.8 and I don't get this issue at all with the tools. My mods on the server side and client side as follows (Installed mods for both sides are exactly the same to prevent de-syncs and other potential issues, and yes I understand some of these are strictly client-side, but I put them in anyways since they tell forge they are client sided and then get disabled during the loading process.) (The log as follows is when I had NTM 2.0.1 installed):
```
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 1.12.2-e586889b
	Operating System: Linux (amd64) version 5.15.0-91-generic
	Java Version: 1.8.0_392, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 5205197328 bytes (4964 MB) / 6415712256 bytes (6118 MB) up to 22906667008 bytes (21845 MB)
	JVM Flags: 1 total; -Xmx24G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                   | Source                                         | Signature                                |
	|:------ |:----------------------- |:------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                    | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                     | 9.42                      | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                 | Magma-1.12.2-e586889b.jar                      | None                                     |
	| LCHIJA | forge                   | 14.23.5.2860              | Magma-1.12.2-e586889b.jar                      | None                                     |
	| LCHIJA | micdoodlecore           | 4.0.6                     | minecraft.jar                                  | None                                     |
	| LCHIJA | mixinbooter             | 8.9                       | minecraft.jar                                  | None                                     |
	| LCHIJA | forgeendertech          | 1.12.2-4.5.6.1            | ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar   | None                                     |
	| LCHIJA | adlods                  | 1.12.2-1.0.8.0            | AdLods-1.12.2-1.0.8.0-build.0504.jar           | None                                     |
	| LCHIJA | adpother                | 1.12.2-1.2.25.0           | AdPother-1.12.2-1.2.25.0-build.0673.jar        | None                                     |
	| LCHIJA | jei                     | 4.16.1.1003               | jei_1.12.2-4.16.1.1003.jar                     | None                                     |
	| LCHIJA | appleskin               | 1.0.14                    | AppleSkin-mc1.12-1.0.14.jar                    | None                                     |
	| LCHIJA | aquaacrobatics          | 1.15.3                    | AquaAcrobatics-1.15.3.jar                      | None                                     |
	| LCHIJA | cummod                  | 1.2.2                     | aquestionablesubstancemod_v1.2.2.jar           | None                                     |
	| LCHIJA | buildcraftlib           | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftcore          | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftbuilders      | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcrafttransport     | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftsilicon       | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftcompat        | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftenergy        | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftfactory       | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftrobotics      | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | bcrf                    | 2.1.3                     | BuildCraftRF-2.1.4.jar                         | None                                     |
	| LCHIJA | carryon                 | 1.12.3                    | carryon-1.12.2-1.12.7.23.jar                   | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-1.0.2.45         | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCHIJA | clumps                  | 3.1.2                     | Clumps-3.1.2.jar                               | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.358                 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux            | 2.1.1                     | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCHIJA | cofhcore                | 4.6.6                     | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCHIJA | cofhworld               | 1.4.0                     | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCHIJA | collective              | 3.0                       | collective-1.12.2-3.0.jar                      | None                                     |
	| LCHIJA | doubledoors             | 2.5                       | doubledoors_1.12.2-2.5.jar                     | None                                     |
	| LCHIJA | galacticraftcore        | 4.0.6                     | Galacticraft-1.12.2-4.0.6.jar                  | None                                     |
	| LCHIJA | sereneseasons           | 1.2.18                    | SereneSeasons-1.12.2-1.2.18-universal.jar      | None                                     |
	| LCHIJA | orelib                  | 3.6.0.1                   | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround               | @VERSION@                 | DynamicSurroundings-1.12.2-3.6.3.jar           | None                                     |
	| LCHIJA | enderstorage            | 2.4.9                     | EnderStorage-1.12.2-2.4.9.jar                  | None                                     |
	| LCHIJA | galacticraftplanets     | 4.0.6                     | Galacticraft-1.12.2-4.0.6.jar                  | None                                     |
	| LCHIJA | mjrlegendslib           | 1.12.2-1.2.1              | MJRLegendsLib-1.12.2-1.2.1.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets            | 1.12.2-0.7.7              | ExtraPlanets-1.12.2-0.7.7.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | fluxnetworks            | 4.1.0                     | FluxNetworks-1.12.2-4.1.1.34.jar               | None                                     |
	| LCHIJA | forgelin                | 1.8.4                     | Forgelin-1.8.4.jar                             | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.2.83                  | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
	| LCHIJA | cfm                     | 6.3.0                     | furniture-6.3.2-1.12.2.jar                     | None                                     |
	| LCHIJA | gravestone              | 1.10.3                    | gravestone-1.10.3.jar                          | None                                     |
	| LCHIJA | tesla                   | 1.0.63                    | Tesla-1.12.2-1.0.63.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | teslacorelib            | 1.0.18                    | tesla-core-lib-1.12.2-1.0.18.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing     | 1.12.2-1.12.2             | industrialforegoing-1.12.2-1.12.13-237.jar     | None                                     |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.7.1              | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCHIJA | levelhearts             | 2.4.0                     | levelhearts-1.12.2-2.4.0.jar                   | None                                     |
	| LCHIJA | mca                     | 6.1.0                     | MCA-1.12.2-6.1.0-universal.jar                 | None                                     |
	| LCHIJA | stevekung's_lib         | 1.3.1                     | stevekung's-lib-mc1.12.2-v1.3.1.jar            | None                                     |
	| LCHIJA | moreplanets             | 2.3.3                     | More-Planets-1.12.2-2.3.3-GC4.0.6.jar          | None                                     |
	| LCHIJA | moreplanetsextras       | 1.12.2-1.0                | MorePlanetsExtras-1.12.2-1.0.jar               | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.4.43                  | MrTJPCore-1.12.2-2.1.4.43-universal.jar        | None                                     |
	| LCHIJA | netherportalfix         | 5.3.17                    | NetherPortalFix_1.12.1-5.3.17.jar              | None                                     |
	| LCHIJA | hbm                     | NTM-Extended-1.12.2-2.0.1 | NTM-Extended-1.12.2-2.0.1.jar                  | None                                     |
	| LCHIJA | performant              | 1.12.2-1.5                | performant-1.11.jar                            | None                                     |
	| LCHIJA | projectred-core         | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-Base.jar           | None                                     |
	| LCHIJA | projectred-integration  | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-integration.jar    | None                                     |
	| LCHIJA | projectred-transmission | 4.9.4.120                 | ProjectRed-1.12.2-4.9.4.120-integration.jar    | None                                     |
	| LCHIJA | refinedstorage          | 1.6.16                    | refinedstorage-1.6.16.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | solarflux               | 12.4.11                   | SolarFluxReborn-1.12.2-12.4.11.jar             | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | soundphysics            | 1.0.10-1                  | Sound-Physics-1.12.2-1.0.10-1.jar              | None                                     |
	| LCHIJA | srparasites             | 1.9.18                    | SRParasites-1.12.2v1.9.16.jar                  | None                                     |
	| LCHIJA | stg                     | 1.12.2-1.2.3              | stg-1.12.2-1.2.3.jar                           | None                                     |
	| LCHIJA | thermalfoundation       | 2.6.7                     | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCHIJA | thermalexpansion        | 5.5.7                     | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCHIJA | thermaldynamics         | 2.5.6                     | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None                                     |
	| LCHIJA | thermalinnovation       | 0.3.6                     | ThermalInnovation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| LCHIJA | wrcbe                   | 2.3.2                     | WR-CBE-1.12.2-2.3.2.33-universal.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | recipehandler           | 0.14                      | YARCF-0.14(1.12.2).jar                         | None                                     |
	| LCHIJA | shetiphiancore          | 3.5.9                     | shetiphiancore-1.12.0-3.5.9.jar                | None                                     |
	| LCHIJA | adchimneys              | 1.12.2-3.5.16.0           | AdChimneys-1.12.2-3.5.16.0-build.0654.jar      | None                                     |
	| LCHIJA | teslacorelib_registries | 1.0.18                    | tesla-core-lib-1.12.2-1.0.18.jar               | None                                     |
```

**Comment by Shibva** [comment] 2024-02-23 19:21
If possible; provide a game log of you doing the actions necessary to cause this issue; it may be possible that something is being printed regarding the issue that could be used. Simply start up a new instance, enter our world and then do this action to cause the desync and close the game. This is best in my opinion to provide a quick and easy log to look through for any possible errors that may be being printed to it.

On a semi related note; I noticed that in the information provided above, but you are running a Linux based operating system. It's highly unlikely that this has some correlation with the issue but the odds that this is the issue is non-zero.

**Comment by Shibva** [comment] 2024-02-23 19:25
In addition, after a quick glance, I've noticed one thing that stands out as a possible red flag; Performant. 

As far as I'm aware, this mod has a very high likelihood of being problematic due to a variety of things that it's capable of doing to improve the performance; some are invasive (altering/modifying hardcode of the game itself) if I recall correctly. Try uninstalling it and see if the issue is present after removing it.

**Comment by Consumedgrub2** [comment] 2024-02-26 10:27
I tried a fresh local server with only HBM v2.0.1 and still got the same issue, and I'm using a regular server jar (not magma) and windows. To add onto this, I did nothing, new world, grabbed a schrabidium pickaxe from the creative menu and tried to cycle the tool ability in survival.
```
[03:25:35] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_401]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_401]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.hbm.util.I18nUtil.resolveKey(I18nUtil.java:8) ~[I18nUtil.class:2.0.1]
        at com.hbm.items.tool.ItemToolAbility.switchMode(ItemToolAbility.java:365) ~[ItemToolAbility.class:2.0.1]
        at com.hbm.items.tool.ItemToolAbility.func_77659_a(ItemToolAbility.java:337) ~[ItemToolAbility.class:2.0.1]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_401]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at com.hbm.util.I18nUtil.resolveKey(I18nUtil.java:8) ~[I18nUtil.class:2.0.1]
        at com.hbm.items.tool.ItemToolAbility.switchMode(ItemToolAbility.java:365) ~[ItemToolAbility.class:2.0.1]
        at com.hbm.items.tool.ItemToolAbility.func_77659_a(ItemToolAbility.java:337) ~[ItemToolAbility.class:2.0.1]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_401]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NullPointerException
```

**Comment by TheSlize** [comment] 2024-02-26 12:41
that was the server trying to do translation while it can only be done on the client side. Fixed in the next update (Alcater please close it)

**Closed as completed** 2024-02-29 19:06 UTC
Labels: Bug, Fixed
