### ISSUE TITLE
Bug: Bedrock Ore not working properly

### ISSUE THREAD

**Issue by xenoulexi** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#318] opened 2024-02-12 06:37 UTC
![image](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/60857805/0a4b2b77-0d24-4710-8f07-a1bf87c3b182)
As you can see, bedrock ore is not working properly...

**Comment by Alcatergit** [comment] 2024-02-14 17:27
Fixed it

**Comment by Shibva** [comment] 2024-02-15 16:09
This is a duplicate of another issue for the record #309

**Closed as completed** 2024-02-15 18:44 UTC
Labels: Bug, Fixed
