### ISSUE TITLE
T60 Armor skin texture clipping bug

### ISSUE THREAD

**Issue by ghost** [Alcatergit/Hbm-s-Nuclear-Tech-GIT#232] opened 2023-09-08 20:13 UTC
![Screenshot_1](https://github.com/Alcatergit/Hbm-s-Nuclear-Tech-GIT/assets/87919245/f255d0ff-4357-44ce-a747-0e687830a456)

**Comment by Shibva** [comment] 2023-09-17 22:36
Duplicate of #227

**Comment by Alcatergit** [comment] 2024-01-08 20:42
That's right

**Closed as completed by Alcatergit** 2024-01-08 20:42 UTC
